laravel-ide-helper:
  description: Laravel IDE Helper, generates correct PHPDocs for all Facade classes, to improve auto-completion.
  url: https://github.com/barryvdh/laravel-ide-helper
  alias: ide-helper
  actions:
    - type: ComposerRequire
      package: barryvdh/laravel-ide-helper
      dev: true
    - type: ArtisanCommand
      command: "vendor:publish"
      args:
        --provider: Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider
        --tag: config
laravel-cors:
  description: Adds CORS (Cross-Origin Resource Sharing) headers support in your Laravel application
  url: https://github.com/fruitcake/laravel-cors
  alias: cors
  actions:
    - type: ComposerRequire
      package: fruitcake/laravel-cors
    - type: ArtisanCommand
      command: "vendor:publish"
      args:
        --tag: cors
    - type: AppendPhpArray
      file: app/Http/Kernel.php
      array: "$middleware"
      value: \Fruitcake\Cors\HandleCors::class
laravel-passport:
  description: Laravel Passport provides OAuth2 server support to Laravel.
  url: https://laravel.com/docs/passport
  alias: passport
  actions:
    - type: ComposerRequire
      package: laravel/passport
    - type: ArtisanCommand
      command: migrate
    - type: ArtisanCommand
      command: "passport:install"
      depends: "artisan migrate"
    - type: AddClassImport
      class: App\User
      import: Laravel\Passport\HasApiToken
    - type: AddTrait
      class: App\User
      trait: HasApiToken
    - type: AddClassImport
      class: App\Providers\AuthServiceProvider
      import: Laravel\Passport\Passport
    - type: AppendPhpMethod
      class: App\Providers\AuthServiceProvider
      method: boot
      append: "Passport::routes();"
    - type: CaptureReplace
      file: config/auth.php
      capture: "~'guards'.*'api'.*'driver' => '(\\w+)'~mUs"
      replacement: passport
laravel-telescope:
  description: An elegant debug assistant for the Laravel framework.
  url: https://laravel.com/docs/telescope
  alias: telescope
  actions:
    - type: ComposerRequire
      package: laravel/telescope
    - type: ArtisanCommand
      command: "telescope:install"
    - type: ArtisanCommand
      command: "telescope:publish"
    - type: ArtisanCommand
      command: migrate
php-cs-fixer:
  description: A tool to automatically fix PHP code style
  url: https://github.com/FriendsOfPHP/PHP-CS-Fixer
  alias: cs-fixer
  actions:
    - type: ComposerRequire
      package: friendsofphp/php-cs-fixer
      dev: true
configure-sqlite:
  description: Setup Laravel .env to use sqlite
  alias: sqlite
  actions:
    - type: CaptureReplace
      file: .env
      capture: "~^DB_CONNECTION=(.*)$~m"
      replacement: sqlite
    - type: CaptureReplace
      file: .env
      capture: "~^(#?D)B_DATABASE=~m"
      replacement: "#D"
    - type: ShellCommand
      command: "touch database/database.sqlite"
fideloper/proxy:
  description: Laravel Proxy Package for handling sessions when behind load balancers or other intermediaries.
  url: https://github.com/fideloper/TrustedProxy
  alias: proxy
  actions:
    - type: ComposerRequire
      package: fideloper/proxy
    - type: ArtisanCommand
      command: "vendor:publish"
      args:
        --provider: Fideloper\Proxy\TrustedProxyServiceProvider
    - type: AppendPhpArray
      file: app/Http/Kernel.php
      array: "$middleware"
      value: \Fideloper\Proxy\TrustProxies::class
laravelcollective/html:
  description: HTML and Form Builders for the Laravel Framework
  url: https://laravelcollective.com/docs/6.0/html
  alias: html
  actions:
    - type: ComposerRequire
      package: laravelcollective/html
barryvdh/laravel-debugbar:
  description: Laravel Debugbar (Integrates PHP Debug Bar)
  url: https://github.com/barryvdh/laravel-debugbar
  alias: debugbar
  actions:
    - type: ComposerRequire
      package: barryvdh/laravel-debugbar
    - type: ArtisanCommand
      command: "vendor:publish"
      args:
        --provider: Barryvdh\Debugbar\ServiceProvider



